### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by jdwh** [kahanu/GolfTracker.DocumentDB#31]
I'm just getting started learning the MEAN stack.  Tried downloading and following the instructions but the page gets stuck at "Loading app..."  I wonder if there have been breaking changes to the packages since this was last updated and I need a specific version of the compilers?  Do any thoughts or version numbers come to mind?  Thanks

![image](https://user-images.githubusercontent.com/18291785/32125601-b6cca070-bb3a-11e7-972f-90e5d65f462e.png)

**Comment by kahanu** [comment]
@jdwh - you need to have a working WebApi service of some sort providing the data for the application.  For this application I was using MongoDB locally for development, and then Azure DocumentDB for production.  If you are going to run this locally, I would install MongoDB locally and then run the MongoDbApi.

If you want a better version that uses Angular 4 (not AngularJS), then look at this repo: https://github.com/kahanu/AzureBootcamp2017 

Either way, you need to have a working data source, like some NoSql database running to make this work.

**Comment by jdwh** [comment]
Thanks for the quick response. I'll take a look at the updated version!!
